### ISSUE TITLE
fix: connection pool robustness — guard against uninitialized pool and broken connection rollback

### ISSUE THREAD

**Issue by Walid-peach** [Walid-peach/MonElu#9]
Two small but meaningful robustness gaps in `api/db.py` introduced with PR #8.

---

### 1. No guard against uninitialized pool

**File:** `api/db.py:27`

If `get_conn()` is called before `init_pool()` (test context, misconfigured startup), the failure is:
```
AttributeError: 'NoneType' object has no attribute 'getconn'
```
Not diagnosable at a glance. Should raise a clear error:
```python
if _pool is None:
    raise RuntimeError("DB pool is not initialized — call init_pool() first")
```

---

### 2. `conn.rollback()` can swallow the original exception on a broken connection

**File:** `api/db.py:31-33`

```python
except Exception:
    conn.rollback()  # if the connection is dead, this also raises — masking the original error
    raise
```
If the DB connection is broken and `rollback()` itself throws, the original exception is replaced. Fix:
```python
except Exception:
    try:
        conn.rollback()
    except Exception:
        pass
    raise
```

---

Both are 5-minute changes in `api/db.py`.
